version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - SQLALCHEMY_DATABASE_URL=postgresql://todos:todos@db:5432/todos
      - ASYNC_SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://todos:todos@db:5432/todos
      - DB_HOST=db
      - DB_USER=todos
      - DB_PASSWORD=todos
      - DB_NAME=todos
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: todos
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
  redis_data:
